class Autogenerated {
  int total;
  List<Items> items;
  PageInfo pageInfo;

  Autogenerated({this.total, this.items, this.pageInfo});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    total = json['total'];
    if (json['items'] != null) {
      items = new List<Items>();
      json['items'].forEach((v) {
        items.add(new Items.fromJson(v));
      });
    }
    pageInfo = json['pageInfo'] != null
        ? new PageInfo.fromJson(json['pageInfo'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['total'] = this.total;
    if (this.items != null) {
      data['items'] = this.items.map((v) => v.toJson()).toList();
    }
    if (this.pageInfo != null) {
      data['pageInfo'] = this.pageInfo.toJson();
    }
    return data;
  }
}

class Items {
  int id;
  String name;
  int authorId;
  String authorName;
  String slug;
  String content;
  String img;
  int statusId;
  String statusName;
  String statusSlug;
  bool displayFlg;
  bool nominated;
  bool nevv;
  bool hot;
  int viewCount;
  int followCount;
  int commentCount;
  int totalChap;
  String lastChapId;
  String lastChapName;
  String lastChapSlug;
  String lastChapUpdated;
  Null chapParName;
  int createdAt;
  String createAtFormated;
  int updatedAt;
  String updateAtFormated;
  String categoryName;
  Null categoryId;
  Null chaps;

  Items(
      {this.id,
      this.name,
      this.authorId,
      this.authorName,
      this.slug,
      this.content,
      this.img,
      this.statusId,
      this.statusName,
      this.statusSlug,
      this.displayFlg,
      this.nominated,
      this.nevv,
      this.hot,
      this.viewCount,
      this.followCount,
      this.commentCount,
      this.totalChap,
      this.lastChapId,
      this.lastChapName,
      this.lastChapSlug,
      this.lastChapUpdated,
      this.chapParName,
      this.createdAt,
      this.createAtFormated,
      this.updatedAt,
      this.updateAtFormated,
      this.categoryName,
      this.categoryId,
      this.chaps});

  Items.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    authorId = json['authorId'];
    authorName = json['authorName'];
    slug = json['slug'];
    content = json['content'];
    img = json['img'];
    statusId = json['statusId'];
    statusName = json['statusName'];
    statusSlug = json['statusSlug'];
    displayFlg = json['displayFlg'];
    nominated = json['nominated'];
    nevv = json['nevv'];
    hot = json['hot'];
    viewCount = json['viewCount'];
    followCount = json['followCount'];
    commentCount = json['commentCount'];
    totalChap = json['totalChap'];
    lastChapId = json['lastChapId'];
    lastChapName = json['lastChapName'];
    lastChapSlug = json['lastChapSlug'];
    lastChapUpdated = json['lastChapUpdated'];
    chapParName = json['chapParName'];
    createdAt = json['createdAt'];
    createAtFormated = json['createAtFormated'];
    updatedAt = json['updatedAt'];
    updateAtFormated = json['updateAtFormated'];
    categoryName = json['categoryName'];
    categoryId = json['categoryId'];
    chaps = json['chaps'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['authorId'] = this.authorId;
    data['authorName'] = this.authorName;
    data['slug'] = this.slug;
    data['content'] = this.content;
    data['img'] = this.img;
    data['statusId'] = this.statusId;
    data['statusName'] = this.statusName;
    data['statusSlug'] = this.statusSlug;
    data['displayFlg'] = this.displayFlg;
    data['nominated'] = this.nominated;
    data['nevv'] = this.nevv;
    data['hot'] = this.hot;
    data['viewCount'] = this.viewCount;
    data['followCount'] = this.followCount;
    data['commentCount'] = this.commentCount;
    data['totalChap'] = this.totalChap;
    data['lastChapId'] = this.lastChapId;
    data['lastChapName'] = this.lastChapName;
    data['lastChapSlug'] = this.lastChapSlug;
    data['lastChapUpdated'] = this.lastChapUpdated;
    data['chapParName'] = this.chapParName;
    data['createdAt'] = this.createdAt;
    data['createAtFormated'] = this.createAtFormated;
    data['updatedAt'] = this.updatedAt;
    data['updateAtFormated'] = this.updateAtFormated;
    data['categoryName'] = this.categoryName;
    data['categoryId'] = this.categoryId;
    data['chaps'] = this.chaps;
    return data;
  }
}

class PageInfo {
  int page;
  int pageSize;
  int offset;
  int totalPage;

  PageInfo({this.page, this.pageSize, this.offset, this.totalPage});

  PageInfo.fromJson(Map<String, dynamic> json) {
    page = json['page'];
    pageSize = json['pageSize'];
    offset = json['offset'];
    totalPage = json['totalPage'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['page'] = this.page;
    data['pageSize'] = this.pageSize;
    data['offset'] = this.offset;
    data['totalPage'] = this.totalPage;
    return data;
  }
}