import 'dart:convert';

import 'package:http/http.dart' as http;
import 'package:manga_reader/model/book.dart';

class URLS {
  static const String BASE_BOOK_URL = "45.76.186.111";
}

class ApiService {
  static String username = 'vinhpq';
  static String password = '12345';
  static String basicAuth =
      'Basic ' + base64Encode(utf8.encode('$username:$password'));
  //Book Search
  static Future<Autogenerated> getSearch(var paramater) async {
    Uri uri = Uri.http('45.76.186.111', '/api/book/search', paramater);
    final response = await http
        .get(uri, headers: <String, String>{'authorization': basicAuth});
    var data = json.decode(utf8.decode(response.bodyBytes));
    // var rest = data["items"] as List;
    // List<Items> list = rest.map<Items>((json) => Items.fromJson(json)).toList();
    // for (int i = 0; i < list.length; i++) {
    //   print(list[i].name);
    // }
    Autogenerated result=Autogenerated.fromJson(data);
    print(result.pageInfo.page);
  }

}
